cache:
  directories:
  - "~/.m2/repository"
  - "~/.cache/pip"
  - $HOME/.ivy2/cache

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
  - stage: test
    language: scala
    scala: 2.12.4
    jdk: openjdk8
    script:
    - sbt test
  - stage: test
    language: python
    jdk: openjdk8
    scala: 2.12.4
    python:
    - 3.6
    install:
    - cd python
    - make
    - pip install --only-binary=numpy,scipy -r requirements.txt
    script:
    - nosetests
  - stage: release
    name: maven central
    language: scala
    scala: 2.12.4
    jdk: openjdk8
    script: sbt ci-release
  - stage: release
    name: pypi
    language: python
    scala: 2.12.4
    jdk: openjdk8
    python: 3.6
    addons:
      apt:
        packages:
        - pandoc
    before_install:
    - cd python
    install:
    - make
    - pip install pypandoc
    - pip install --only-binary=numpy,scipy -r requirements.txt
    script: true
    deploy:
      provider: pypi
      skip_cleanup: true
      user: CitrineInformatics
      password:
        secure: fb/NiAH7E1zA2iRUT+NMywH7dh0HF3qLM/JhjWLQWQ8l/pxOy7HPgk1CDEkZip/4emH2ur5+bGAD0pm0ewfDWfvjTPA+woV5IEebK2KL3Gm4Oam4fZP27NZ5zfYs6Q1dx3YPjRUgI3gtJ+0Y1tVKvZrUaZHityDMJDuEsYjdmPnFsA6s6U/5GYeQfWaYjZcflqYd01H8K9kbCeBsRBlOUm1lCXmt13R4uBOoMNAkuR7knYUOE1VM6VJWTN2T0iKphS9agxPHh/9/B9gjCQExhynOWSs5E2WhhDnWUoAJgyaZdxZQOxT2jJKA4dJGMCtyQScWItjsglcpthd+DsNtx/0vF1fDV3tvdjRVfegnhcF9fMUeI30O5jGTqNhimkiQsV1L+Sn6LFVAJKZ2yGzjqyS+8wn/uGOLQ04R46aw7KcfDJthzPU+dx0W78scTnkOnOx0R6eLH/HBn619h415JSsYpQ/D4A2VzODhHfScgzEe9xoL61ArhYz/wAqEAvit8WbFs4D7ZVnBc/98wsBD2NKUlmTZfkjPDAZQr49S1Na6UKlK6p4gLkXE6hfwgkFwxLiaQxOMfg0u/7VbbJzfrB2568HerS/oilDq+Bp+jNKUwyo08P0qD+8a4Gif1uk1UcipixDWbCvNlfr1H7+2FrN0+b92Xmfjd+CTMKmfv7o=
      distributions: sdist bdist_wheel
      on:
        tags: true