addSbtPlugin("com.github.sbt"   % "sbt-ci-release" % "1.5.11")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"       % "1.4.1")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"   % "1.2.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.11.3")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
