name: Deploy to PyPI

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install SBT
        uses: olafurpg/setup-scala@v11
        with:
          java-version: '11'
      - name: Build Scala project
        run: sbt assembly
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build Python package
        run: |
          cd python
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}