name: Deploy-Maven

on:
  push:
    branches:
      - '**'
    tags: ['*']

env:
  JAVA_VERSION: 11

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.PGP_SECRET }}
        passphrase: ${{ secrets.PGP_PASSPHRASE }}
    - name: Release to Maven Central
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      run: |
        sbt clean compile
        sbt publishSigned
        sbt sonatypeRelease