name: Deploy

on:
  push:
    branches: [main]
    tags: ['*']

env:
  JAVA_VERSION: 11

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'
    - name: Release to Maven Central
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      run: sbt ci-release
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies for PyPI release
      run: |
        sudo apt-get install -y pandoc
        cd python
        make
        pip install --only-binary=numpy,scipy -r requirements.txt
    - name: Build and publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd python
        python setup.py sdist bdist_wheel
        pip install twine
        twine upload dist/*
      if: startsWith(github.ref, 'refs/tags/')