name: Deploy-Maven

on:
  release:
    types: [published]

env:
  JAVA_VERSION: 11

jobs:
  publish:
    name: Publish package to Maven
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'
    - name: Install SBT
      uses: olafurpg/setup-scala@v11
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Release to Maven Central
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      run: sbt ci-release
