name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SCALA_VERSION: 2.13.8
  JAVA_VERSION: 11

jobs:
  test-scala:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'
    - name: Cache SBT dependencies
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
          ~/.m2
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Run Scala tests
      run: |
        sbt -Dsbt.log.noformat=true scalafmtCheckAll
        sbt -Dsbt.log.noformat=true +test

  test-python:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        cd python
        make
        pip install --only-binary=numpy,scipy -r requirements.txt
        pip install -r test_requirements.txt
    - name: Run Python tests
      run: |
        cd python
        nosetests